name: Fork Sync

permissions:
  contents: write
  workflows: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: huangxd-/danmu_api
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false
